services:
  - type: web
    name: ltii-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://ltii.vercel.app
    healthCheckPath: /health
    autoDeploy: true
